services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=appdb

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
